export const MenuList = [
    {item: 'Simple', price: 230, category: 'Pizzas'},
    {item: 'Completa', price: 887, category: 'Pizzas'},
    {item: 'Fiesta', price: 1230, category: 'Pizzas'},
    {item: 'Especial', price: 1550, category: 'Pizzas'},
    {item: 'Vegana', price: 1375.76, category: 'Pizzas'},
    {item: 'Simple', price: 895, category: 'Hamburguesas'},
    {item: 'Completa', price: 1295.50, category: 'Hamburguesas'},
    {item: 'Especial', price: 1317.50, category: 'Hamburguesas'},
    {item: 'Simple', price: 1317.50, category: 'Ensaladas'},
    {item: 'Primavera', price: 1317.50, category: 'Ensaladas'},
    {item: 'De Frutas', price: 1317.50, category: 'Ensaladas'},
    {item: 'Chocolate 1kg', price: 1800, category: 'Helados'},
    {item: 'Vainilla 1kg', price: 1800, category: 'Helados'},
    {item: 'Frutilla 1kg', price: 1800, category: 'Helados'},
    {item: 'Granizado 1kg', price: 1800, category: 'Helados'},
    {item: 'Dulce de Leche 1kg', price: 1800, category: 'Helados'},
    {item: 'Menta 1kg', price: 1800, category: 'Helados'},
    {item: 'Kinder 1kg', price: 1800, category: 'Helados'},
    {item: 'Banana con Dulce 1kg', price: 1800, category: 'Helados'},
    {item: 'Chocotorta 1kg', price: 2740.94, category: 'Helados'},
    {item: 'Limon', price: 1800, category: 'Frutas'},
    {item: 'Banana', price: 1800, category: 'Frutas'},
    {item: 'Uvas', price: 1800, category: 'Frutas'},
    {item: 'Cerezas', price: 1800, category: 'Frutas'},
    {item: 'Pera', price: 1800, category: 'Frutas'},
    {item: 'Manzana', price: 1800, category: 'Frutas'}
]